spring:
***REMOVED***kafka:
***REMOVED******REMOVED***bootstrap-servers: localhost:9092
***REMOVED******REMOVED***producer:
***REMOVED******REMOVED******REMOVED***key-serializer: org.apache.kafka.common.serialization.StringSerializer
***REMOVED******REMOVED******REMOVED***value-serializer: org.apache.kafka.common.serialization.StringSerializer
***REMOVED***application:
***REMOVED******REMOVED***name: TelegramParser
api_id: 3969182
api_hash: 707e2ae05e8a8749e42b688bd61c5fc5
session_dir: ./sessions